GET  http://localhost:3000/api/product
    ?category=""
    &priceMin=""
    &priceMax=""
    &sort=""
    &order=""

Content-Type: application/json

###

GET  http://localhost:3000/api/product/anas

Content-Type: application/json